/**************************************************************************
 Program:  Voices_q15_recode.sas
 Library:  Voices
 Project:  NeighborhoodInfo DC
 Author:   P. Tatian
 Created:  09/19/17
 Version:  SAS 9.4
 Environment:  Local Windows session (desktop)
 
 Description:  Read recoded Q15 data generated by Python program and
create final recoded data set. 

 Modifications: 10/18/17 LH replaced break vars code with standard macro. 
		10/23/17 LH modified recoding from Natural Language Processing
		10/30/17 LH finished recoding and added vars for tables
		11/01/17 LH added code for case level response
**************************************************************************/

%include "L:\SAS\Inc\StdLocal.sas";

** Define libraries **;
%DCData_lib( Voices )

filename fimport "L:\Libraries\Voices\Raw\Q15_recode.csv" lrecl=1000;

proc import out=Q15_recode
    datafile=fimport
    dbms=csv replace;
  datarow=2;
  getnames=yes;
  guessingrows=max;
run;

data Q15_recode_random;

  set Q15_recode;

  where recode not in ( '', 'NOMATCH' 'LOCATION');
  
  r = ranuni( -1 );
  
  format _all_ ;
  informat _all_ ;

  if caseid=4001 then respnum=2; *for some reason respnum is 1 in Q15_recode when Q15_text1='' in Voices.VoicesDMVSurvey2017; 
  
run;

proc sort data=Q15_recode_random;
  by caseid respnum r;
run;

data Q15_recode_unq;

  set Q15_recode_random;
  by caseid respnum;
  
  if first.respnum;
  
  drop r;
  
run;
data location;
	
	set Q15_recode; 

	where recode = 'LOCATION';

run; 
proc sort data=location nodupkey;

	by caseid respnum;

data Q15_recode_unq_1 (drop=recode_l);

	merge Q15_recode_unq (in=a)
		  location (in=b keep=caseid respnum recode rename=(recode=recode_l));
	by caseid respnum;

	if recode='' and b=1 then recode=recode_l;

run;
proc transpose data= Voices.VoicesDMVSurvey2017  out=voices_full_q15;

	by caseid;
	var Q15_Text1 Q15_Text2 Q15_Text3; 

run;
data voices_full_q15_1 (drop=_name_);

	set voices_full_q15 (drop=_label_);

		respnum=.;
		if _name_="Q15_Text1" then respnum=1;
		if _name_="Q15_Text2" then respnum=2;
		if _name_="Q15_Text3" then respnum=3;

		rename col1=Q15_Text;
run; 
data Voices_Q15_toreview;

 	merge Q15_recode_unq_1 (rename=(recode=Q15_recode) drop=entity fuzzratio )
    	   voices_full_q15_1 ;
  	by caseid respnum;

  		Q15_text=propcase(Q15_text);

run;

%let list='ENTERTAINMENT' 'FOOD' 'CULTURE' 'MUSEUMS' 'MONUMENTS' 'PERFORM' 'ARTS' 'SPORTS' 'NIGHTLIFE' 'JOBS' 'PEOPLE' 'LOCATION' 'DIVERSITY' 'TRANSPORTATION' 'BUS' 'METRO'
    'AIRPORTS' 'NATURE' 'COMMUNITY' 'SCHOOLS' 'WEATHER' 'LIFE' 'FAMILY' 'SHOPPING' 'SERVICES' 'CAPITAL' 'ECONOMY' 'NOTHING' 'SAFETY' 'HOUSING' 'DC' 'POLITICS' 'WALKABILITY'
    'COSTS' '';

%macro printlist;

%do i=1 %to 35;
%let var=%scan(&list,&i.," ");

proc freq data=Voices_Q15_toreview;
tables Q15_Text ;
where  Q15_recode=&var.;
Title2 "Coded as &var"; 

run;
%end; 

title2;

%mend;

%printlist;

data Voices_Q15_newrecode (drop=diversity culture politics capital monuments transpo metro jobs food nightlife entertain services people);

	set Voices_Q15_toreview;

			culture=index(Q15_text,"Cultural Activ");
			culture=culture+index(Q15_text,"Cultural Events");
			culture=culture+index(Q15_text,"Cultural Sites");
			culture=culture+index(Q15_text,"Cultural Venues");
			culture=culture+index(Q15_text,"Cultural Places");
			culture=culture+index(Q15_text,"Cultyural Events");
			culture=culture+index(Q15_text,"Cutural Events");
			culture=culture+index(Q15_text,"Access To Cultural Institutions"); *was in location;
			culture=culture+index(Q15_text,"Access To Cultural/Historical Resources");*was in location;
			culture=culture+index(Q15_text,"Access To Free Cultural");*was in location;
			culture=culture+index(Q15_text,"Cultural Access");*was in location;
			culture=culture+index(Q15_text,"Proximity To Cultural Institutions");*was in location;
			culture=culture+index(Q15_text,"Proximity To Cultural And Historic");*was in location;

			politics=index(Q15_text,"Dynamic Politics");
			politics=politics+index(Q15_text,"Proximity To Political Protest");
			politics=politics+index(Q15_text,"Political Climate"); *was in weather;
			politics=politics+index(Q15_text,"Exciting Atmosphere Politically"); *was in life;
			politics=politics+index(Q15_text,"Liberal/Progressive"); *was in life;
			politics=politics+index(Q15_text,"Liberal Government"); *was in life;
			politics=politics+index(Q15_text,"Liberal Population");

			capital=index(Q15_text,"Home Of The Presidents");
			capital=capital+index(Q15_text,"The Proximity To The Center Of Us House");
			capital=capital+index(Q15_text,"Access To Political Leader");
			capital=capital+index(Q15_text,"Access To Politicians");
			capital=capital+index(Q15_text,"Federal Legislative Process");
			capital=capital+index(Q15_text,"Access To Government Buildings");
			capital=capital+index(Q15_text,"Political Events");
			capital=capital+index(Q15_text,"Being At The Center Of Politics");
			capital=capital+index(Q15_text,"Being Close To National Politics");
			capital=capital+index(Q15_text,"National Policy");

			monuments=index(Q15_text,"National History Events");
			monuments=monuments+index(Q15_text,"Access To Educational/Historical");
			monuments=monuments+index(Q15_text,"Access To Historic Sites");
			monuments=monuments+index(Q15_text,"Access To Historic Loca");
			monuments=monuments+index(Q15_text,"Access To Historical Sites");
			monuments=monuments+index(Q15_text,"Access To Historical/Cult");
			monuments=monuments+index(Q15_text,"Near Many Historical Loca");
			monuments=monuments+index(Q15_text,"Access To Historical And Cult");
			monuments=monuments+index(Q15_text,"Access To Historical & Cult");
			monuments=monuments+index(Q15_text,"Access To Historical Sites");
			monuments=monuments+index(Q15_text,"Access To Historical Loca");
			monuments=monuments+index(Q15_text,"Proximity To Historical Sites");


			jobs=index(Q15_text,"Legal Activities"); *was in entertainment;
			jobs=jobs+index(Q15_text,"Access To Different Industr"); *was in location;
			jobs=jobs+index(Q15_text,"Access To Iobs"); *was in location;
			jobs=jobs+index(Q15_text,"Asccess To Work As A Contractor"); *was in location;
			jobs=jobs+index(Q15_text,"Employment Opportunities Related To"); *was in diversity;
			if Q15_text in("Government Employment" "Internships" "Nice Job Placements" "Work Options" "Excellent Place To Work" "Good Job Environment" "Good Work History" 
					"Good Pay" "Good Payouts" "Great Place To Work" "Great Work Place" "Great Workforce" "High Employment Rate" "Job Options" "Job Outlook"
					"Job Prospects" "Job Wages Are High" "Job/Career Opportunities" "Many Employers" "Professional Opportunities" "Professional Opportunity"
					"The Job Market/Economy" "Training Programs" "Work Availability" "Emploment Opportunities" "Employers" "Employment Market" "Employment Opportunitiies"
					"Fairly Good Pay" "Good Employment Prospects" "High Pay" "High Pay Scale" "Higher Pay" "Opportunities For Advancement" "Opportunity To Be Highly Compensated"
					"Opportunity For Advancement" "Pay" "Pay Is Good." "Pay Rate" "Pay Scale" "Rate Of Pay" "The Pay"
) then jobs=1; 

			diversity=index(Q15_text,"Different Cultu");
			diversity=diversity+index(Q15_text,"Diverse Cultu");
			diversity=diversity+index(Q15_text,"Diverese Cultu");
			diversity=diversity+index(Q15_text,"Diversity Of Cultu");
			diversity=diversity+index(Q15_text,"Diversity Of People");
			diversity=diversity+index(Q15_text,"Diversity Of Resident");
			diversity=diversity+index(Q15_text,"Diversity Of Popul");
			diversity=diversity+index(Q15_text,"Encountering People From Differ");
			diversity=diversity+index(Q15_text,"Countless Cultu");
			diversity=diversity+index(Q15_text,"The Culture Range");
			diversity=diversity+index(Q15_text,"Differnt Cult");
			diversity=diversity+index(Q15_text,"Varies Cultu");
			diversity=diversity+index(Q15_text,"Variety Of Cultu");
			diversity=diversity+index(Q15_text,"Variety Of Peopl");
			diversity=diversity+index(Q15_text,"People From Different Countries");
			diversity=diversity+index(Q15_text,"People From Different Places");
			diversity=diversity+index(Q15_text,"Cultural Mix");
			diversity=diversity+index(Q15_text,"Different Groups Of Peop");
			diversity=diversity+index(Q15_text,"Different Types Of Peop");
			diversity=diversity+index(Q15_text,"Diverse Group Of Peop");
			diversity=diversity+index(Q15_text,"Diverse Peop");
			diversity=diversity+index(Q15_text,"Diverse Popul");
			diversity=diversity+index(Q15_text,"Diverse, Interesting People");
			diversity=diversity+index(Q15_text,"Diverse/International");
			diversity=diversity+index(Q15_text,"Diversified Pop");
			diversity=diversity+index(Q15_text,"Diversity Of The Peop");
			diversity=diversity+index(Q15_text,"Diversity Of The Popul");
			diversity=diversity+index(Q15_text,"Ethnically Diverse");
			diversity=diversity+index(Q15_text,"Know People From Other");
			diversity=diversity+index(Q15_text,"Diversity Of Diffent People");
			diversity=diversity+index(Q15_text,"Mix Of People");
			diversity=diversity+index(Q15_text,"Interacting W/People From All");
			diversity=diversity+index(Q15_text,"Interesting Cross-Section Of Peop");
			diversity=diversity+index(Q15_text,"It Has Many Races Of");
			diversity=diversity+index(Q15_text,"International City");
			diversity=diversity+index(Q15_text,"Meeting All Kinds Of Peopl");
			diversity=diversity+index(Q15_text,"Multi Cultur");
			diversity=diversity+index(Q15_text,"Multi Ethnic");
			diversity=diversity+index(Q15_text,"Nice Mix Of People");
			diversity=diversity+index(Q15_text,"People Come From All Over");
			diversity=diversity+index(Q15_text,"People From All Over");
			diversity=diversity+index(Q15_text,"People From All Around");
			diversity=diversity+index(Q15_text,"People From Diverse");
			diversity=diversity+index(Q15_text,"People Of All Types");
			diversity=diversity+index(Q15_text,"Large Array Of People");
			diversity=diversity+index(Q15_text,"The Mixture Of People");
			diversity=diversity+index(Q15_text,"Different Color Skins");
			diversity=diversity+index(Q15_text,"Cosmopolitan Population");
			diversity=diversity+index(Q15_text,"Diverse Community");
			diversity=diversity+index(Q15_text,"Diverse Ethnicity");
			diversity=diversity+index(Q15_text,"Ethnic Neighborhoods/Cultures");
			diversity=diversity+index(Q15_text,"Very Diverse Neighborhoods");
			diversity=diversity+index(Q15_text,"Diversity (People)");
			diversity=diversity+index(Q15_text,"Varitety Of Residents");
			diversity=diversity+index(Q15_text,"Diverse Demographic");
			diversity=diversity+index(Q15_text,"Demographically Diverse");
			diversity=diversity+index(Q15_text,"Multi-Cultu");
			diversity=diversity+index(Q15_text,"Multi-Ethnic");

			food=index(Q15_text,"Food From");
			food=food+index(Q15_text,"Diversity Of Cuisine"); 
			food=food+index(Q15_text,"Diversity Of Food"); 
			food=food+index(Q15_text,"Diversity Of Restaurants");
			food=food+index(Q15_text,"Diversity Of Resteraunts");
			food=food+index(Q15_text,"Great Food In Tremendous Diversity");
			food=food+index(Q15_text,"Diverse Eating Places");

			nightlife=index(Q15_text,"Dance Clube");
			nightlife=nightlife+index(Q15_text,"Going To The Clubs");
			nightlife=nightlife+index(Q15_text,"Good Night Life");


			services=index(Q15_text,"Free Help Services");
			services=services+index(Q15_text,"So Many Resources");
			services=services+index(Q15_text,"Access To Good Medical");
			services=services+index(Q15_text,"Access To Most Household Services");
			services=services+index(Q15_text,"Access To My Karate");
			services=services+index(Q15_text,"Access To Resources");
			services=services+index(Q15_text,"Access To Top Medical");
			services=services+index(Q15_text,"Full Social Security"); *was in safety; 

			entertain=index(Q15_text,"Access To Recreational Facilities");
			entertain=entertain+index(Q15_text,"Access To Recreational Spots");
			entertain=entertain+index(Q15_text,"Access To Recreation Zone");
			entertain=entertain+index(Q15_text,"Entertaining Things To Do");
			if Q15_text="A Lot Of Amusment Parks" then entertain=1;
			if Q15_text in("A Lot Of Things To Do" "A Lot To Do" "All Of The Family Activities Available" "Always Lots To Do" "Entertainment Experience" "It Has Lots Of Stuff To Do"
						 "Many Things To Do" "Lots Of Free Things To Do" "Lots Of Fun Stuff For Kids" "Lots Of Stuff To Do" "Lots Of Things To Do" "Lots To Do" 
						"Plenty Of Things To Do" "So Many Things To Do" "So Much To Do" "The Attractions" "There Is Entertainment Spritz Thouhout The Dmv"
						"Things To Do" "Tons Of Things To Do" "Lot To Do" "Movies" "Abundance Of Activities And Amenities"  "Lot's Of Things To Do"
						 "Lots Going On" "Lots Of Attractions" "Lots Of Attractions And Things To Do" "Lots Of Free Things To See And Do" "Lots Of Interesting Things To Do"
						"Lots Of Things Going On" "Lots Of Things To Do If I Want To Do Them" "Lots Of Things To See And Do"
						"Lots Of Things To See And Do And Participate In"  "Stuff To Do" "The Many Things To See And Do Here" "Movie Theaters"
						 "Plenty Of Variety In Things To Do Or See" "Plenty To Do" "So Many Productive Things To Do In The Area."  "So Much To See And Do"
						"Something Is Always Going On" "Terrific Attractions (Many Of Them Are Free)" "There Are Always Things To Do" "There Are Hidden Gems To Explore Everywhere"
						"There Are Lots Of Things To Do Here" "There Are Many Entertainment Venues." "There Are Plenty Of Things To Do" "There Is A Lot Going On." "There Is A Lot To Do And See"
						"There Is Always Something Happening" "There Is Always Something To Do" "There Is Lot To Do" "There Is So Much To Do" "There's Always Something Going On" "There's Always Something To Do"
						"There's Always Something To Do." "There's Lots To Do" "Theres So Much To Do" "The Things To Do" "Things Do And See" "Thingss To Do" "Thinhs To Do" "Tons Of Free Things To Do"
						"Tons To Do" "Varied Attractions" "Variety Of Attractions" "Variety Of Things To Do" "Family Activities" "Festivities"  
						"Interesting Things To Do" "Many Places To Go Have A Good Time" "Many Things To See And Do" "Entertaining" "Entertainment Offering" "Entertainment Venues"
						"Embassy Galas" "Drum Circles" "Duckpin Bowling" "Attractions" "Six Flags" "Proximity To Many Free Attractions" "Bars, Clubs, Music Venues, Variety in Dining" 
						"Free Attractions" "Free Festivities") then entertain=1;
			metro=index(Q15_text,"Metro Accesibility");
			metro=metro+index(Q15_text,"Metro Accessiblity");
			if Q15_text in("Easy Metro Access" "Metro Access" ) then metro=1;
			if Q15_Text in("Metro" "Metro Accessible" "Metro Accessibility" "Metro Accessibility To Most Places" "Metro Accessibility To The City"
							"Dca Metro" "Metro" "Metro Transportation" "Meteo" "Metro Accesessible" "Metro Accesible" "Metro Accessable" "Metro Andbus Good Comunication"
							"Metro Convience" "Metro Options" "Metro Station" "Metro Subway Availability" "Metro System" "Metro System Availabilty"
							"Effective Metro System" "Good Metro System" "Subway" "Subways" "Near Metro" "Metro Andbus Good Comunication" ) then metro=1;

			transpo=index(Q15_text,"Public Transit"); *was metro;
			if Q15_text in("Nice Transit" "Mass Transit" "Transit" "Easy Travel & Transit" "Calles" "Decent Transporation Links" "Easy To Get Around" "Easy To Travel To Other Places"
							"Transportstio" "Travel Options" "It's Easy To Get Around" "Ability To Bike To Work" "Access To Transport Options" "Trains"
							"Local Transit System" "Loads Of Travel Options" "Slug Line" "Somewhat Reliable Transportation Systems" "Transit Systems" "Transportation Access"
							"Transportation Choices" "Transportation Ease" "Transportation Hub" "Travel" "Travel Convenience" "Travel Hub" "Travel Is Easy" "Good Transportation Network"
							"You Can Get Around Very Easily, Train, Uber Etc.." "Good Hub For Local, Regional, National And International Travel" "Highway" "Neigborhood Transportation"
							"No Driving" "Easy To Get To Most Things" "Easy To Get Around The City" "Easy To Get Elsewhere" "Easy Togo To Many Places" "Easy To Travel Other Places"
							"Easy To Move Around" "Ease Of Travel" "Decent Roadways" "Commute To Work" "Convient For Commute To Work" "Ease Of Commute To Work" "Easy Commute To Work")  then transpo=1;

			people=index(Q15_text,"Affluent Communities");
			people=people+index(Q15_text,"Citizens Are Highly Educated"); 
			people=people+index(Q15_text,"People With Money"); 

			if culture > 0 then Q15_recode="CULTURE";
			else if politics > 0 then Q15_recode="POLITICS";
			else if capital > 0 then Q15_recode="CAPITAL";
			else if monuments > 0 then Q15_recode="MONUMENTS";
			else if jobs > 0 then Q15_recode="JOBS";
			else if food > 0 then Q15_recode="FOOD";
			else if diversity > 0 then Q15_recode="DIVERSITY";
			else if nightlife > 0 then Q15_recode="NIGHTLIFE";
			else if services > 0 then Q15_recode="SERVICES";
			else if entertain > 0 then Q15_recode="ENTERTAINMENT";
			else if people > 0 then Q15_recode="PEOPLE";
			else if metro > 0 then Q15_recode="METRO";
			else if transpo > 0 then Q15_recode="TRANSPORTATION";
			

			if Q15_text in("Nothingnothinh" "Nuthing" "Zip" "Everything Sucks" "Hate It") then Q15_recode="NOTHING"; 
			if Q15_Text="Networking" then Q15_recode="COMMUNITY"; *was jobs;
			if Q15_text in("Fine Churches" "Communities" "In Good Nabourhood" "Convenient Religious Facilities" "Residential" "Residential Areas" "Sense Of Belonging" "Your Chose Of Where To Worship."
					"Good Neigbor" "Easy To Get Involved") then Q15_recode="COMMUNITY"; 
			if Q15_text="Mix Of Local And Urban Communities" then Q15_recode="COMMUNITY";*was diversity;

			if Q15_Text="Police Does Its Work" then Q15_recode="SAFETY"; *was jobs;
			if Q15_text in("Safe Community" "Safe Neighborhoods" "Safety For Children" "Safe" "Safe Area" "Safe Place" "Seguridad" "Segurity" "Mucha Seguridad"
						   "Generally Safe" "Lowcrime Rate" "Not Many Drugs" "Not Many Crimes" "Not Much Crime / Police Activity" 
						   "Safe In Fairfax" "Safe Neighborhood" "Safe Place To Live." "Safer Than Usual" "Relatively Peaceful" "Relatively Safe" 
						   "Somewhat Safe" "Feel Secure" "It Is Safe" "It's Safe") then Q15_recode="SAFETY";

			if Q15_Text="Access To International Flights Out Of Iad" then Q15_recode="AIRPORTS";
			if Q15_Text in("Proximity To Dulles Airport" "Gateway To The World-Airports" "International Airports") then Q15_recode="AIRPORTS";

			if Q15_text="Diversity Of Cultural Opportunities" then Q15_recode="CULTURE";*was diversity;
			if Q15_text in("Cultural Amenities" "Excellent Cultural Amenities") then Q15_recode="CULTURE";*was services;
			if Q15_text in("Cultural Things" "Cultural Resources" "Cultured" "Culturally Strong" "Cultural/Historical" "Cultural Opportunities" "Excellent Cultural Venues"
							"Nearby Cultural Facilities" "Free Cultural Opportunities" "The Cultural Amenities" "Large Amount Of Many Types Of Culteral And Historical Activities"
						    "Cultural Life" "Cultural Vibrancy" "Many Opportunities For Cultural And Educational Experiences" "Lots Of Cultural Things To Do"
						    "Rich Cultural Life" "Wealth Of Cultural Heritage/Historical Sites" "Lots Of Things To Do Culturally" "The Cultural Assets"
						   "Plenty Of Cultural Attractions" "Rich Cultural Opportunities" "Social And Cultural Opportunities" "Excellent Cultural Opportunities"
						  "Near Cultural Centers" "Free Cultural Institutions" ) then Q15_recode="CULTURE";

			if Q15_text in ("Muesm M" "Washington Dc Museums" "Access To Museums And In Dc" "Museums & Activities" "Museums And Activities" "Nuseums"
					"Miseums" "Nice Activities, Museums" "Museam" "Museum/Culture Opportunities" "Musiums" "Musumes" "Muesums" "The National Zoo"
					"Smithsonian Institute Museums" "The Musemes" "Library Of Congress" "National Gallery Of Arts" "Near Washington Museums"
					"Free Museum Visit") then Q15_recode="MUSEUMS";

			if Q15_text in("Very Walkable" "Easy To Walk To Destination" "Easy To Walk To Places I Need To Go" "Ability To Walk To Area Bus And Rest" "Walkable Communities, Good Transit" 
					"Walkable, Fun Neighborhoods" "Walk Every Where" "Walk" "Walkable Areas" "Walkable City" "Walkibility" "Walkihg" "Walking" "Walking Places"
					"You Can Walk Around The City" "Everything Is Close And Walkable" "Great For Walking During The Day" "Can Walk To A Lot Of Things (In My Neighborhood)") then Q15_recode="WALKABILITY"; 

			if Q15_text="The National Mall Is Just A Half Hour Away By Metro" then Q15_recode="MONUMENTS"; *was metro;
			if Q15_text in("Fountains" "Historic" "Historic Places To Visit" "Historic Resources" "Historical Sites" "Historically Strong" "Historical Locations" "Martin Luther King Mermeriol"
							"National Mall Very Nice" "Sight Seeing" "Tourtist"  "The Historic Buildings, Histo" "It Is Full Of Historical Information And Sites."
							"Memorials" "Historic Areas" "Historic Places" "Historic Sites" "Historical" "Historical Attractions" "Historical Places" "Historical Places To Visit"
							"Historical Significance" "Historical/Cultural Attractions" "Historically Interesting" "Historically Rich" "Historically Significant Venues To Visit" 
							"History Access" "Mpnument" "Lots Of Historical Places To See"  "Not Far From Historical And Cultural Centers" "Supreme Historical Importance"
							"The Historical Buildings" "The Historical Sites" "The Washington Monument" "Water Features" "Famous Buildings" "Lincoln Memorial"
						"The Sight-Seeing" "The Sites" "The Sites You Can Visit" "Site Seeing" "Sites" "Sight's" "Sightingseeing" "Great Site Seeing Area"
						 "Places To Go And See" "Places To Visit" "Places To Visit Close By" "Place To See" "So Many Places To Visit" "Lots Of Place Around" "Lot's To,see" "Lots Of Places To Visit"
					"The Places"  "Places To See" "Things To See" "Places To Go" "Lot Of Things To See" "So Much To See" "Interesting Places To Discorver" "Interesting Places To Visit" 
					"Lots Of Things To See" "Lots To See" "Tourism Options" "Tourist" "Tourist Spot" "Tourist Spots" "Tourists Spots" "Tours" "Unknown Places I Find To Visit I Didnt Know Excist"
			"When Folks Visit Me, I Get To Be A Tour Guide!!" "It's A Tourist Area") then Q15_recode="MONUMENTS";

			if Q15_text in("Clubs/Restaurants" "Night Scene") then Q15_recode="NIGHTLIFE";
			if Q15_text in("It's A Major City" "Major City" "Unlike Any Other Major Us City. A Flavor Of Its Own (Though It's Changing)."
						"Big City" "Big City But Not So Big With No High Rise Building"  "Big City But Not Too Intense") then Q15_recode="DC"; 

			if Q15_text in("High Quality Public School System" "School District" "Schooling" "Good School And Parks In My Neighborhood" "Good Schools For Children" "Good Schools for Son" "Educationally Strong"
					"Education Ops In The Area" "Educational" "Educational Experience" "Educational Opportunites" "Educational Opportunities" "Educational Opportunities (Beyond High School)" 
					"Quality Montgomery Schools" "Fairfax County School System" "Fairfax County Schools" "Excellent Educational Opportunities" "Good Educational Institutions"
					"Good Achools" "Free Preschool" "Grade Schools" "Lower And Higher Education Institutions" "Outstanding Public Educational System" "The Educational System In Fairfax"
					"Learning Institutions" "Learning/Teaching Opportunities" ) then Q15_recode="SCHOOLS";

			if Q15_text in("Have Four Seasons" "Four Seasons" "Four Seasons Fully Experienced"  "4 Different Weather Patterns" "El Clima" "Few Natural Disasters" "Hot" "The Heat" "The Rain" "Variable Weather Conditions W/O Excess"
					"Spring" "Spring And Fall" "Warm And Sunny" "Warm Summers" "Warmer In The Winter" "Warmer Than Ny" "We Get All Four Seasons" "Wheater" "Fall" "It Rarely Snows."
					"Whether")then Q15_recode="WEATHER";

			if Q15_text in("Affordable" "And It Is Kind Of Not To Pricy" "Cheaper Than New York" "Expensive" "You Need Money To Live Here" "A Little Cheaper Than California"
						"Expenses" "Lower Grocery Prices" "Not Too Expensive" "Things To Do That Are Free" "It's Cheap" "It's Expensive And That Keeps Out The Riff Raff") then Q15_recode="COSTS";

			if Q15_text in("Area Urbana" "Centrally Located For Travel Abroad" "Close To Big Cities" "Close To City" "Close To DMV" "Close To Everything" "Close To Lots Of Stuff"
					"Close To Pennsylvania" "Close To Places" "Close To Two Major Cities" "Close To West Virginia" "Close To Work" "Connivence" "Convenient" "Convenient To Everything"
					"Convient" "Every Thing Is Close" "Everything Is Convient" "Everything Is Close" "Everything Is Close By" "Halfway Between Ca And France"
					"Access To Other Communities" "It Is Convient" "Its Close To Everything I Need" "Near The City" "Close To Dmv" "Everything In Convient"
					"Convenience To Many Areas" "Convenience To Nearby Cities" "Convience" "Convnience" "Convenience To Places" "Convenience" "Conveinience"
					"It Is Very Convenient Living Here" "The Convenience." "Locale" "Locality" "Located Near Some Very Nice Cities I.E. New York, Jersey Shore And Philadelphia"
					"Locstion" "Lots Of Other Nearby States To Visit" "Short Trip To Many Other Cities" "Things Ar Close By" "Things Are Close" "You Have Three Cities Within A Easy Drive"
					"You Can Either Live In The Suburbs, City, Or Rural Areas And Be Within Each Within A Matter Of Minutes" "Everything It's Close" "Everything Is Close By My Residence" "Everything Is Convenient"
					"Everything Is Here" "Everything Is Nearby" "Everything Is Relatively Close (Compared To Larger States)" "Have Everything Around You" "Very Close To Umd"
					"Living Location Options" "Easy And Accessibale" "Asseccisibility" "Very Exseccable" "Comvience" "Conevnience" "Conveinence" "Convence" "Convenient To Everything You Need"
							"Convenirnce" "Convienebce" "Convienence" "Convince" "Convinent" "Generally Easy To Get Around") then Q15_recode="LOCATION";

			if Q15_text in("Ammentities" "Programs For Seniors" "Lot Of Programs For Seniors" "Rockville Senior Center" "Excellent Medical Facilities And Physicians" "Hospital Care" "Medical Facilities" "Medical Quality"
					"Avaiable Facilities" "Resources" "Resources And Support" "Excellent Medical Facilities" "Outstanding Medical Facilities" "Convenience Of Services" "Good Medical Facilities" "Good Medical Support"
					"The Medical Providers I See Are Nearby." "Rich In Community Resources" "Recreational Centers" "Health Care Choices" "Health Facilities" "Quality Medical Facilities"
					"Supermarkets" "Variety Of Resources" "You Can Get Al The Help That You Need" "You Can Get Help" "You Have An Enormous Amount Of Resources" "Facilities"
					"Good Facilities" "Good Programs" "Government Programs" "Govermenr Assists" "Great Human Services Resource" "Great Place For Help" "Librariea" "Library" 
					"Near Market" "Paid Youth Programs" "Huge Resources At Hand" "Early Start Programs" "Available Facilities" "We Could Easily Get Grocery Items" ) then Q15_recode="SERVICES";

			if Q15_text="Prestigious African American Communities" then Q15_recode="PEOPLE"; *was diversity;
			if Q15_text in("Successful Black Profesionals" "Babes" "Buenas Personas" "Buenas Persona" "Human Quality" "Gilrs" "Everyone Knows Everyone" "Son Personas Unidas"
					"High Education Peoples" "High Educational Level" "Highly Educated Citizenry" "Lots Of Educated, Entrepreneurial Types" "Social Opportunities" "Society"
					"Young Adults" "Young Profess" "Youth" "Everyone Is Friendly" "Poeple" "Populated Area" "Population Density" "Engaged Citizens"
					"Girl" "Girls") then Q15_recode="PEOPLE";

			if Q15_text in("Beautiful" "Beautiful Areas" "Es Muy Bonito" "El Paisaje" "Green Spaces" "Proximity To Scenic Areas" "Lovely" "Pretty" "The Views" "Tree Lined Streets"
					"Good Outdoor Spaces" "The Natural Areas Surrounding Dc For Activities" "Recreation Activities" "Recreation Options" "Recreation/Entertainment Opportunities" "Recreational Areas"
					"Tree" "Recreational Opportunities" "Running Trails" "Scenic" "See The Sky" "Sky" "State Parks" "Sun" "Super Green And Flowery" "Trail System--Good For A City"
					"Trail Systems" "Variety Of Outdoor Places" "Variety Of Recreational Opportunities" "Excellent Natural Places To Visit" "Flowers" "Foliage" "Grass"
					"Green Areas" "Green Enviroment" "Greenspace" "Healthy Soil For Gardening" "It Has Many Scenic Views" "It's Beautiful" "It's Beautiful Out Here"
					"It's Pretty" "It's A Beautiful Place To Live" "It Is Beautiful" "More Green Spaces Than A Lot Of Metro Area" "National Park System"
					"Natural Beauty" "Natural Beauty Of D, M, V" "Natural Places Close Enough For Day Trip" "Nature Centers Are Close" "Near Great Falls National Park"
					"Near The Seashore" "Nearness To C &o Canal Park" "Open Areas" "Outdoor Areas" "Outdoor Recreation Opportunities" "Outdoors Not So Far Away" "Outdoors Opportunities"
					"Parcs, Geen Spaces" "Park" "Park Land" "Places To Walk" "Places To Walk- Trails" "River Access" "Running" "Boating" "Cycling" "The Area Is Beautiful"
					"Gardens" "Forests" "Fresh Air" "Geography" "More Green Spaces Than A Lot Of Metro Areas") then Q15_recode="NATURE";

			if Q15_text in("Wealth Opportunity" "Relative Economic Stability" "Prosperity" "Income Potential" "Indifferent To Economic Cycles" "Centros Comerciales" "Economically Vabraint" "Employment Rates Seem High" 
					"Entrepreneurial Experience" "Economically Diverse" "Income Ranges" "Government Contracts" "Government Economy" "Entreprenuership"
					"Economic" "High Income" "The Affluence" "Tax Rates" "Imcome" "Economic Development" "Everyones Rich" "Economic Opportunities" "Economic Opportunity" "Economic Stability" "Economically Vibrant") then Q15_recode="ECONOMY";

			if Q15_text in("Intellectual Climate" "Social Climate" "Ambiente" "Calm" "Chill" "Choice Of Living" "Cool" "Crowded" "Crowd" "Es Muy Calida El Area" "Friendly"
					"Good Social Scene" "Happy" "Harmony" "Excited" "Fair" "It Is A Very Adventurous City" "It's Cool" "It's Fun" "It's Nice" "Kindness" "Peaceful" "Quiet"
					"Unique" "Intellectual Opportunities" "Intellectual Rigor" "Intellectual Stimulation" "Intellectually Stimulating" "Weed"
					"Hip" "Cool Place" "Sophistication" "Southern Charm" "The Style/Way Of Living" "The Vibe (There's Always Something Interesting And Important Happening)"
					"Young Professional Town" "Fast" "Fast-Paced" "Liveliness" "Lively" "Lively Area" "Legal Weed" "One Of A Kind Of Place" "Open Mindedness"
					"Work Life Balance"  "Professional Environment" "Up Beat Vibe" "Work/Life Better Than Nyc" "Elite" "Energy" "Ambiance" "High Living Standards"
					"High Class" "High Standards Of Living" "It Is A Very Adventurous City." "It's Uncommonly" "Its Vibrant" "Life Quality" "Live Is Good"
					"Peace" "Peace And Quiet" "Peaceful Place To Live" "Peacifull" "Peasfull" "Pleasant City" "Pleasant Environment" "Quality Of Life" "Queer-Friendly"
					"Standard Of Living" "Very Dense Area - You Can Find Everything You Need In A Small Radius, No Need To Drive Far Away" "Very Physical Active Place"
					"Vibrant" "Vital Urban Environment" "Excitement" "Exciting" "Exciting City" ) then Q15_recode="LIFE";

			if Q15_text in("Cosmopolitan" "Culturally Diverse" "Culturally Diversified" "Culturally Diverse." "Diverse" "Good Choices In Diverse Places To Be Around" "Multicultural" "Very Diverse"
				"Multicultural Environment" "Multi Languages" "Mix Cultures" "Cosmopitalian" "Cosmopolitan City" "Cosmopolotism" "Rich Mix Of Nationalities" "This Is A Very Diverse Area."
				"Ethnic Variety" "International /Diversity Of Population" "International Feeling" "International Flavor" "International Presents" "National Area/Ethinicly Diverse"
				"The Ethnic Groups" "Diverse Metropolitan Area" "Diverse Area" "Diverse Citizenship" "Different Ethnicity" "International" "Multi-Cuture Environment")then Q15_recode="DIVERSITY";

			if Q15_text in("Good Restzuranrs" "Eateries" "Eating Place" "Eating" "Fresh Fish" "Mumbo Sauce" "Places To Eat" "A Lot Of Eateries" "Maryland Bile Crabs" "Maryland Crabs"
					"Food Availability" "Food Court" "Food Delivery" "Food Fair" "Food Options" "Food Trucks" "Food Venues" "Vegan Food" "Ethiopian Food"
					"Lots Option Restaurant" "Lot Of Places To Eat." "Lots Of Places To Eat" "Sushi" "The First Thing I Love About The Washington Area, Is The Food Truck. There's Just So Much Of Them."
				"The Mom And Pop Restaurants" "The Large Selection Of Goid Restaurants" "Plenty Of Variety In Places To Eat" "Plenty Of Things To Eat" "Place To Eat"
				"Great Places To Eat" "Great Restaurahrs" "Red Lobster" "They Have The Best Mamb Sauce" "Variety Of Eating Establishments" "Doughnuts" "Downtown Restaurants"
				"Diverse Eating Places" "Dinner"  "Breweries") then Q15_recode="FOOD";
					
			if Q15_text in("Political Center" "The Nation's Eyes Are Focused On This Area" "Hub Of Nation's Governance" "Nation Capitol" "It Were The White House At" "First Hand Law Making" "Government Center"
					"Political Pulse Of The Nation" "It Is Us Capitol" "Pride In Being At The Center Of The Free World" "The U.S Capitol" "Where Decisions Are Made" "Federal Buildings" 
					"Federal Gov." "Global/National Relevance" "Heartbeat Of The Nation" "Living In A World Capital" "Near National Politics Center" "Importance" "Important Area") then Q15_recode="CAPITAL";

			if Q15_text in("The Music Scene" "Lots Of Free Or Affordable Classical Music Listening Opportunities" "Good Theater/Arts Performances" "Go Go" "Easy Access To Live Theater Performances"
					"Shows" "Music Concerts" "Great Music Scene" "Great Performance Arts" "Having Quality Radio Stations To Listen To" "The Theater Scene" "Theatre Community"
					"Wolftrap" "Many Performing Arts" "National Symphony") then Q15_recode="PERFORM";
					
			if Q15_text in("Living With My Spouse" "Proximity Tonfamily" "Family Friendly" "Most Of My Fanily Is Here" "My Family Is Happy." "My Kids" "My Mother" "Good Area To Raise Kids"
							) then Q15_recode="FAMILY";

			if Q15_text in("New Developments Are Rising Daily" "Housing Programs" "My House" "Property Values Remains Pretty Consistently High" "Real Estate Prices" "Real Estate Values"
					"Value Of Property" "Decent Real Estate Market") Then Q15_recode="HOUSING";
					
			if Q15_text in("Plenty Of Places To Buy Things Needed" "Store Locations Are Convenient" "Store Selection" "Numerous Places To Shop" "Plenty Of Shopping Venues"
					"Shop" "Shopping Choices" "Shopping Is Asseccable" "Shopping Nearby" "Shopping Stores" "Reston Town Center" "Retail Options"
					"Has Convenient And Good Shopping Places" "Many Corner Stores") Then Q15_recode="SHOPPING";
			
			if Q15_text in("Political" "Political Active" "Political Activism Is Strong" "Political Environment" "Political Focus" "Political Hot Pot" "Political Involvement" 
					"Political Scene" "Political/Social Awareness" "Politically Engaged" "Progressive" "Progressive Outlook" "Public Policy/Public Affairs Focus" "Watching Political Circus"
					"Demoratic" "Fairly Socially Liberal (Despite Current Administration)" "Government Town" "Liberal" "Liberal Politically" "Maryland Still Supports The Aca"
					"Being In The Center Of Political Life" "Think Tanks") then Q15_recode="POLITICS";
					
			If Q15_text in("Spoert" "Sport" "Sport Events" "Access To College And Pro Sports" "Nationals" "Nats" "Plays/Sporting Events." "Professional & Collegiate Sports"
					"Washington Capitals" "Washington Nationals" "Washington Redskins") then Q15_recode="SPORTS";

			/*Carl's additions 10/25/17*/;						
			if Q15_text in("A City That's Easy To Navigate" "Accessible By Modes Other Than Auto" "Accessible" "Commuting") Then Q15_recode="TRANSPORTATION";			
			if Q15_text in("A Good Economic City.") Then Q15_recode="ECONOMY";			
			if Q15_text in("A Beautiful Place To Live" "Air" "Architectural And Natural Beauty" "Beauty Of The Region"
							"Burke Lake" "City, But Good Outdoorsy Vibe" "Beautiful Area" "Beautiful Area Of Country"
							"Beautiful Landscaping" "Beautiful Place" "Beautiful Places" "Beautiful In Its Own Weird Way"
							"Beauty" "Beauty Of Area" "Beauty Of Spring" "Beauty Places" "Beautyful" "Attraction Of Beauty"
							"Close To Natural Attractions" "County Parks") Then Q15_recode="NATURE";			
			if Q15_text in("420-Friendly" "Accessibility - Lifestyle" "Active" "Active, Health-Conscious City" "Close To Water Activities (Fishing)"
							"City Living" "City Like But Homie" "Being A Aprt Of A Pool" "Calm Area" "Calmness" "Bustling" "Busy"
							"Comfortable" "Comfortable Surroundings"  ) Then Q15_recode="LIFE";	
			if Q15_text in("A Little Cheaper Than California" "A Lot Of Free Things To Do" "A Lot Of Things To Do, Many Are Free"
                           "A Lot To See And Do That Is Free" "A Lot To See/Do For Free" "Cheaper" "Cost Og Living") Then Q15_recode="COSTS";	
			if Q15_text in("A Lot Of Eateries" "Brunch" "Carry Out" "Chicken") Then Q15_recode="FOOD";	
			if Q15_text in("A Variety Of Entertaining Things To Do In Virginia" "A Lot Of Different Types Of Things To Do"
							"Abundant Things To Do" "Activies" "All The Things To Do" "All Ways Something To Do"
							"Alot Of Things To Do" "Always Fun Things To Do" "Always Something Going On" 
							"Always Something Happening" "Always Something New To Discover." "Always Something To Do"
   							"Always Something To Do/Sites To See" "Always Something To See Or Do" "Always Things To Do"
							"Always Things To Do And Experience" "Amount Of Things To Do" "And There Is Plenty Of Things To Do In The Metropolitan Area"
							"Availability Of Things To Do" "Big Name Entertainment Comes Here" "Casino") Then Q15_recode="ENTERTAINMENT";	
			if Q15_text in("Availability Of Decent Metro System") Then Q15_recode="METRO";	
			if Q15_text in("Botanical Garden") Then Q15_recode="MUSEUMS";
			if Q15_text in("Able To Walk" "Clarendon Is Walkable") Then Q15_recode="WALKABILITY";	
			if Q15_text in("A Place Of Importance" "A Sense Of Being Connected To An Important International Venue"
                           "Ability To Influence National Policy" "Being Near National News" "Being Near The State Department For Which I Work Parttime"
							"Center Of Action" "Center Of Attention" "Center Of Government Activity" "Center Of National Government" "Center Of The World"
							"Close To Political Action" "Close To The National Action" "Close To What's Going On In The Nation" "Close To World News"
							"Close To The Action") Then Q15_recode="CAPITAL";	
			if Q15_text in("Able To Buy A Home" "Basements") Then Q15_recode="HOUSING";	
			if Q15_text in("Activism" "Black Leadership") Then Q15_recode="POLITICS";	
			if Q15_text in("Adequate Shopping Facilities And Competition Between Them." ) Then Q15_recode="SHOPPING";	
			if Q15_text in("Alot To Do For Families" "Close To My Parents" "Close To Home" "Close To Where I Grew Up") Then Q15_recode="FAMILY";	
			if Q15_text in("Always Working In The Private Sextor" ) Then Q15_recode="JOBS";
			if Q15_text in( "County Safety") Then Q15_recode="SAFETY";
			if Q15_text in("And The Thought Me How To Dab" ) Then Q15_recode="CULTURE";
			if Q15_text in("Attitudes" "Boyfriend" "Boys" "Chicks" ) Then Q15_recode="PEOPLE";
			if Q15_text in("Being Only A Few Hours Away From Other Big Cities" "Between Maryland And Virginia" "Center Between Nyc And Orlando"
							"Central To Other Area Of Interest" "Close Destination" "Close Distance" "Close Places" "Close To A City"
							"Close To A Great City" "Close To A Lot Of Things" "Close To An International Hub" "Close To Annapolis"
							"Close To Attractions" "Close To Big City" "Close To Delaware, Maryland And Virginia" "Close To Evertyhing"
							"Close To Everything I Need" "Close To New York" "Close To Ny" "Close To Other States" "Close To Things"
							"Close To Many Big Cities" "Close To Lots Of Places" "Close To Larger Cities" "Close To Many Things" "Close To The City"
							) Then Q15_recode="LOCATION";
			if Q15_text in("Chocolate City" "Close To Downtown D.C. Tour Attractions") Then Q15_recode="DC";
			if Q15_text in("Climate - Seasons" "Absence Of Most Natural Desasters") Then Q15_recode="WEATHER";
			if Q15_text in("Close To Metro" ) Then Q15_recode="METRO";
			if Q15_text in("Close To Friedns" ) then Q15_recode="COMMUNITY"; 
			if Q15_text in("Close To Historic Sites" "Close To Historical Sites" "Cool Historic Sites" "Buildings Of Entrest") then Q15_recode="MONUMENTS"; 
			if Q15_text in("College Assistance" "Close To My Alma Mater" "Continuing Education Activities") then Q15_recode="SCHOOLS";
			if Q15_text in("County Financial Support" "County Services" "County Support Activities For Seniors") then Q15_recode="SERVICES"; 
			if Q15_text in("Better Educated") then Q15_recode="PEOPLE"; 
			if Q15_text in("Cultural" "Cultural Accesible" "Cultural Advantages" "Cultural And Civic Offerings" "Cultural And Historical Attractions"
							"Cultural And Historical Venues" "Cultural Areas" "Cultural Aspects" "Cultural Attractions" "Cultural Availabilities"
							"Cultural Availability" "Cultural Center" "Cultural Environment" "Cultural Experience" "Cultural Experiences" "Cultural Exposure"
							"Cultural Hub" "Cultural Institutions" "Cultural Offerings" "Cultural Opportunity" "Cultural Options" "Cultural Things To Do"
							"Cultural Variety" "Cultural/Historical Sites" "Culture - Much Of Which Is Available For Free" "Cutlure") then Q15_recode="CULTURE"; 
			if Q15_text in("Cultural And Sports Events") then Q15_recode="SPORTS"; 


run;
			

%macro printlist_new;

%do i=1 %to 35;
%let var=%scan(&list,&i.," ");

proc freq data=Voices_Q15_newrecode;
tables Q15_Text ;
where  Q15_recode=&var.;
Title2 "Coded as &var"; 

run;
%end; 

title2;

%mend;

%printlist_new;

proc sort data=Voices_Q15_newrecode;
	by caseid;

data Voices_Q15_recode;

	merge Voices_Q15_newrecode 
		  Voices.VoicesDMVSurvey2017 (keep=caseid weight dov_urban ppethm ppracem ppeducat ppincimp ppage ppgender pprent  PPT01 PPT25 PPT612 PPT1317);
	by caseid;

		%make_break_vars_2017;

	label respnum="Survey Response Number"
		  Q15_recode="Q15 recoded categories: 3 best things about living in Washington area"
		  Q15_text="Q15 actual response: 3 best things about living in Washington area"
		  ;

		if Q15_recode="FOOD" then Q15_3a=1; else if Q15_recode ~="FOOD" then Q15_3a=0;
		if Q15_recode="ENTERTAINMENT" then Q15_3b=1; else if Q15_recode ~="ENTERTAINMENT" then Q15_3b=0;
		if Q15_recode="JOBS" then Q15_3c=1; else if Q15_recode ~="JOBS" then Q15_3c=0;
		if Q15_recode="DIVERSITY" then Q15_3d=1; else if Q15_recode ~="DIVERSITY" then Q15_3d=0;
		if Q15_recode="LOCATION" then Q15_3e=1; else if Q15_recode ~="LOCATION" then Q15_3e=0;
		if Q15_recode="CULTURE" then Q15_3f=1; else if Q15_recode ~="CULTURE" then Q15_3f=0;
		if Q15_recode="MONUMENTS" then Q15_3g=1; else if Q15_recode ~="MONUMENTS" then Q15_3g=0;
		if Q15_recode="PEOPLE" then Q15_3h=1; else if Q15_recode ~="PEOPLE" then Q15_3h=0;
		if Q15_recode="NATURE" then Q15_3i=1; else if Q15_recode ~="NATURE" then Q15_3i=0;
		if Q15_recode="MUSEUMS" then Q15_3j=1; else if Q15_recode ~="MUSEUMS" then Q15_3j=0;
		if Q15_recode in("TRANSPORTATION" "BUS") then Q15_3k=1; else if Q15_recode not in("TRANSPORTATION" "BUS") then Q15_3k=0;
		if Q15_recode="SCHOOLS" then Q15_3l=1; else if Q15_recode ~="SCHOOLS" then Q15_3l=0;
		if Q15_recode="COMMUNITY" then Q15_3m=1; else if Q15_recode ~="COMMUNITY" then Q15_3m=0;
		
		if Q15_Text='' then do;
			Q15_3a=.; Q15_3b=.; Q15_3c=.; Q15_3d=.; Q15_3e=.; Q15_3f=.; Q15_3g=.; Q15_3h=.; Q15_3i=.; Q15_3j=.; Q15_3k=.; Q15_3l=.; Q15_3m=.;
		end;
		
		label Q15_3a="Q15 All Responses: Food"
			  Q15_3b="Q15 All Responses: Entertainment"
			  Q15_3c="Q15 All Responses: Jobs"
			  Q15_3d="Q15 All Responses: Diversity"
			  Q15_3e="Q15 All Responses: Location"
			  Q15_3f="Q15 All Responses: Culture"
			  Q15_3g="Q15 All Responses: Monuments and history"
			  Q15_3h="Q15 All Responses: People"
			  Q15_3i="Q15 All Responses: Nature"
			  Q15_3j="Q15 All Responses: Musuems"
			  Q15_3k="Q15 All Responses: Transportation"
			  Q15_3l="Q15 All Responses: Schools"
			  Q15_3m="Q15 All Responses: Community"
			  ;

		if respnum=1 then do;
			if Q15_recode="FOOD" then Q15_1a=1; else if Q15_recode ~="FOOD" then Q15_1a=0;
			if Q15_recode="ENTERTAINMENT" then Q15_1b=1; else if Q15_recode ~="ENTERTAINMENT" then Q15_1b=0;
			if Q15_recode="JOBS" then Q15_1c=1; else if Q15_recode ~="JOBS" then Q15_1c=0;
			if Q15_recode="DIVERSITY" then Q15_1d=1; else if Q15_recode ~="DIVERSITY" then Q15_1d=0;
			if Q15_recode="LOCATION" then Q15_1e=1; else if Q15_recode ~="LOCATION" then Q15_1e=0;
			if Q15_recode="CULTURE" then Q15_1f=1; else if Q15_recode ~="CULTURE" then Q15_1f=0;
			if Q15_recode="MONUMENTS" then Q15_1g=1; else if Q15_recode ~="MONUMENTS" then Q15_1g=0;
			if Q15_recode="PEOPLE" then Q15_1h=1; else if Q15_recode ~="PEOPLE" then Q15_1h=0;
			if Q15_recode="NATURE" then Q15_1i=1; else if Q15_recode ~="NATURE" then Q15_1i=0;
			if Q15_recode="MUSEUMS" then Q15_1j=1; else if Q15_recode ~="MUSEUMS" then Q15_1j=0;
			if Q15_recode in("TRANSPORTATION" "BUS") then Q15_1k=1; else if Q15_recode not in("TRANSPORTATION" "BUS") then Q15_1k=0;
			if Q15_recode="SCHOOLS" then Q15_1l=1; else if Q15_recode ~="SCHOOLS" then Q15_1l=0;
			if Q15_recode="COMMUNITY" then Q15_1m=1; else if Q15_recode ~="COMMUNITY" then Q15_1m=0;
		end;
		
		if Q15_Text='' then do;
			Q15_1a=.; Q15_1b=.; Q15_1c=.; Q15_1d=.; Q15_1e=.; Q15_1f=.; Q15_1g=.; Q15_1h=.; Q15_1i=.; Q15_1j=.; Q15_1k=.; Q15_1l=.; Q15_1m=.;
		end;
		if respnum in (2 3) then do;
			Q15_1a=.n; Q15_1b=.n; Q15_1c=.n; Q15_1d=.n; Q15_1e=.n; Q15_1f=.n; Q15_1g=.n; Q15_1h=.n; Q15_1i=.n; Q15_1j=.n; Q15_1k=.n; Q15_1l=.n; Q15_1m=.n;
		end;

		label Q15_1a="Q15 1st Response: Food"
			  Q15_1b="Q15 1st Response: Entertainment"
			  Q15_1c="Q15 1st Response: Jobs"
			  Q15_1d="Q15 1st Response: Diversity"
			  Q15_1e="Q15 1st Response: Location"
			  Q15_1f="Q15 1st Response: Culture"
			  Q15_1g="Q15 1st Response: Monuments and history"
			  Q15_1h="Q15 1st Response: People"
			  Q15_1i="Q15 1st Response: Nature"
			  Q15_1j="Q15 1st Response: Musuems"
			  Q15_1k="Q15 1st Response: Transportation"
			  Q15_1l="Q15 1st Response: Schools"
			  Q15_1m="Q15 1st Response: Community"
			  ;
run;


 
proc format;

  value $Q15_r
    'ENTERTAINMENT' = "Food and entertainment options"
    'CULTURE' = "Culture and history"
    'JOBS' = "Jobs and career opportunities"
    'PEOPLE' = "Types of people who live here"
    'LOCATION' = "Location and accessibility"
    'DIVERSITY' = "Diversity"
    'TRANSPORTATION' = "Transportation options"
    'NATURE' = "Natural environment"
    'COMMUNITY' = "Community"
    'SCHOOLS' = "Schools and educational institutions"
    'WEATHER' = "Climate and weather"
    'LIFE' = "Lifestyle"
    'FAMILY' = "Family in area"
    'SHOPPING' = "Shopping options"
    'SERVICES' = "Services and amenities"
    'CAPITAL' = "It's the nation's capital"
    'ECONOMY' = "Economy"
    'NOTHING' = "Nothing"
    'SAFETY' = "Crime and safety"
    'HOUSING' = "Housing"
    'DC' = "Washington, DC"
    'POLITICS' = "Political culture"
    'WALKABILITY' = "Walkability"
    'COSTS' = "Cost of living";

  value $Q15_r_det
    'ENTERTAINMENT' = "Entertainment"
    'FOOD' = "Food"
    'CULTURE' = "Culture"
    'MUSEUMS' = "Museums"
    'MONUMENTS' = "Monuments"
    'PERFORM' = "Performing arts"
    'ARTS' = "Arts"
    'SPORTS' = "Sports"
    'NIGHTLIFE' = "Nightlife"
    'JOBS' = "Jobs"
    'PEOPLE' = "People"
    'LOCATION' = "Location"
    'DIVERSITY' = "Diversity"
    'TRANSPORTATION', 'BUS' = "Transportation"
    'METRO' = "Metro"
    'AIRPORTS' = "Airports"    
    'NATURE' = "Nature"
    'COMMUNITY' = "Community"
    'SCHOOLS' = "Schools"
    'WEATHER' = "Weather"
    'LIFE' = "Lifestyle"
    'FAMILY' = "Family"
    'SHOPPING' = "Shopping"
    'SERVICES' = "Services"
    'CAPITAL' = "Nation's capital"
    'ECONOMY' = "Economy"
    'NOTHING' = "Nothing"
    'SAFETY' = "Crime & safety"
    'HOUSING' = "Housing"
    'DC' = "Washington, DC"
    'POLITICS' = "Political culture"
    'WALKABILITY' = "Walkability"
    'COSTS' = "Cost of living";
  value $blank
    ' ' = 'BLANK'
    other = 'NOT BLANK';


%Finalize_data_set( 
  data=Voices_Q15_recode,
  out=Voices_Q15_recode,
  outlib=Voices,
  label="VoicesDMV survey, 2017, Q15 recoded responses",
  sortby=caseid respnum,
  revisions=%str(Added bus to transportation Q15_3k, Q15_1k)
)

proc freq data=Voices_Q15_recode;
  tables Q15_text * Q15_recode / list missing;  
  format Q15_text $blank. Q15_recode $Q15_r_det.;
  title2 'CHECK FOR MISSING RECODES: ALL RESPONSES';
run;

proc freq data=Voices_Q15_recode;
  where respnum = 1;
  tables Q15_text * Q15_recode / list missing;  
  format Q15_text $blank. Q15_recode $Q15_r_det.;
  title2 'CHECK FOR MISSING RECODES: FIRST RESPONSE ONLY';
run;

proc print data=Voices_Q15_recode n;
  where Q15_text = '' and Q15_recode ~= '';
  id caseid respnum;
  var Q15_text Q15_recode;
  title2 'CODED BLANK RESPOSE';
run;

proc print data=Voices_Q15_recode n;
  where Q15_text ~= '' and Q15_recode = '';
  id caseid respnum;
  var Q15_text;
  title2 'UNCODED RESPONSES';
run;

proc freq data=Voices_Q15_recode order=freq;
  weight weight;
  tables Q15_recode;  
  format Q15_recode $Q15_r_det.;
  title2 'All responses';
run;
proc freq data=Voices_Q15_recode order=freq;
  where respnum=1;
  weight weight;
  tables Q15_recode;  
  format Q15_recode $Q15_r_det.;
  title2 'First response only';
run;
** Word cloud export **;

proc summary data=Voices_Q15_recode nway;
  class Q15_recode;
  var weight;
  output out=A sum=;
  format Q15_recode $Q15_r_det.;
run;


data Word_cloud;

  length Q15_recode $ 20 wc_weight 8;
  
  set A;
  
  wc_weight = round( weight );
  
  keep Q15_recode wc_weight;
  
run;

filename fexport "&_dcdata_default_path\Voices\Raw\Voices_q15_recode_wordcloud.txt" lrecl=256;

proc export data=Word_cloud
    outfile=fexport
    dbms=tab replace;

run;

filename fexport clear;

*ADD CODE TO GET # of PEOPLE WHO SAID X*;

proc summary data=voices_Q15_recode;
	by caseid;
	var Q15_3: ;
	output out=voices_Q15_recode_sum_0 sum=;
run; 

data voices_Q15_recode_sum (drop=Q15: _type_ _freq_);
	
	Merge voices_Q15_recode_sum_0
		  Voices.VoicesDMVSurvey2017 (keep=caseid weight dov_urban ppethm ppracem ppeducat ppincimp ppage ppgender pprent  PPT01 PPT25 PPT612 PPT1317);
	by caseid;

	%make_break_vars_2017;

	sQ15_3a=.;
	If Q15_3a > 0 then sQ15_3a=1; if Q15_3a=0 then sQ15_3a=0;
	sQ15_3b=.;
	If Q15_3b > 0 then sQ15_3b=1; if Q15_3b=0 then sQ15_3b=0;
	sQ15_3c=.;
	If Q15_3c > 0 then sQ15_3c=1; if Q15_3c=0 then sQ15_3c=0;
	sQ15_3d=.;
	If Q15_3d > 0 then sQ15_3d=1; if Q15_3d=0 then sQ15_3d=0;
	sQ15_3e=.;
	If Q15_3e > 0 then sQ15_3e=1; if Q15_3e=0 then sQ15_3e=0;
	sQ15_3f=.;
	If Q15_3f > 0 then sQ15_3f=1; if Q15_3f=0 then sQ15_3f=0;
	sQ15_3g=.;
	If Q15_3g > 0 then sQ15_3g=1; if Q15_3g=0 then sQ15_3g=0;
	sQ15_3h=.;
	If Q15_3h > 0 then sQ15_3h=1; if Q15_3h=0 then sQ15_3h=0;
	sQ15_3i=.;
	If Q15_3i > 0 then sQ15_3i=1; if Q15_3i=0 then sQ15_3i=0;
	sQ15_3j=.;
	If Q15_3j > 0 then sQ15_3j=1; if Q15_3j=0 then sQ15_3j=0;
	sQ15_3k=.;
	If Q15_3k > 0 then sQ15_3k=1; if Q15_3k=0 then sQ15_3k=0;
	sQ15_3l=.;
	If Q15_3l > 0 then sQ15_3l=1; if Q15_3l=0 then sQ15_3l=0;
	sQ15_3m=.;
	If Q15_3m > 0 then sQ15_3m=1; if Q15_3m=0 then sQ15_3m=0;

		label sQ15_3a="Q15 Any Response: Food"
			  sQ15_3b="Q15 Any Response: Entertainment"
			  sQ15_3c="Q15 Any Response: Jobs"
			  sQ15_3d="Q15 Any Response: Diversity"
			  sQ15_3e="Q15 Any Response: Location"
			  sQ15_3f="Q15 Any Response: Culture"
			  sQ15_3g="Q15 Any Response: Monuments and history"
			  sQ15_3h="Q15 Any Response: People"
			  sQ15_3i="Q15 Any Response: Nature"
			  sQ15_3j="Q15 Any Response: Museums"
			  sQ15_3k="Q15 Any Response: Transportation"
			  sQ15_3l="Q15 Any Response: Schools"
			  sQ15_3m="Q15 Any Response: Community"
			  ;

run;
%Finalize_data_set( 
  data=voices_Q15_recode_sum,
  out=voices_Q15_recode_sum,
  outlib=Voices,
  label="VoicesDMV survey, 2017, Q15 recoded responses summarized to caseid",
  sortby=caseid,
  revisions=%str(New file.)
)

